import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from fpdf import FPDF
import os

plt.rcParams['mathtext.fontset'] = 'stix'
plt.rcParams['font.family'] = 'STIXGeneral'

fig, ax = plt.subplots(figsize=(8, 7))
x1_vals = np.linspace(0, 5, 400)

c1_x2 = (12 - 4*x1_vals) / 2
c2_x2 = 10 - 4*x1_vals
c3_x2 = 4 - x1_vals

ax.plot(x1_vals, c1_x2, 'b-', linewidth=2, label='$4x_1 + 2x_2 = 12$')
ax.plot(x1_vals, c2_x2, 'r-', linewidth=2, label='$4x_1 + x_2 = 10$')
ax.plot(x1_vals, c3_x2, 'g-', linewidth=2, label='$x_1 + x_2 = 4$')

vertices = np.array([[0, 0], [2.5, 0], [2, 2], [0, 4]])
polygon = plt.Polygon(vertices, alpha=0.2, color='cyan', label='Feasible Region')
ax.add_patch(polygon)

corners = [(0, 0), (2.5, 0), (2, 2), (0, 4)]
for (cx, cy) in corners:
    ax.plot(cx, cy, 'ko', markersize=8)
    ax.annotate(f'({cx}, {cy})', (cx, cy), textcoords="offset points",
                xytext=(10, 8), fontsize=11, fontweight='bold')

ax.plot(2, 2, 'r*', markersize=20, zorder=5)
ax.annotate('Degenerate BFS\n(2, 2): 3 constraints binding',
            (2, 2), textcoords="offset points", xytext=(15, -30),
            fontsize=11, fontweight='bold', color='red',
            arrowprops=dict(arrowstyle='->', color='red', lw=1.5))

ax.set_xlim(-0.3, 5)
ax.set_ylim(-0.3, 7)
ax.set_xlabel('$x_1$', fontsize=14, fontweight='bold')
ax.set_ylabel('$x_2$', fontsize=14, fontweight='bold')
ax.set_title('Question 4(ii): Feasible Region with Degenerate BFS', fontsize=14, fontweight='bold')
ax.legend(fontsize=10, loc='upper right')
ax.grid(True, alpha=0.3)
ax.axhline(y=0, color='k', linewidth=0.5)
ax.axvline(x=0, color='k', linewidth=0.5)
plt.tight_layout()
plt.savefig('q4_graph.png', dpi=150, bbox_inches='tight')
plt.close()

class PDF(FPDF):
    def header(self):
        pass
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')

pdf = PDF('P', 'mm', 'Letter')
pdf.alias_nb_pages()
pdf.set_auto_page_break(auto=True, margin=20)
pdf.set_left_margin(15)
pdf.set_right_margin(15)

def title_section(pdf, text):
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(0, 32, 96)
    pdf.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

def subtitle(pdf, text):
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(0, 70, 140)
    pdf.cell(0, 7, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)

def body(pdf, text):
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5.5, text)
    pdf.ln(1)

def body_bold(pdf, text):
    pdf.set_font('Helvetica', 'B', 10)
    pdf.multi_cell(0, 5.5, text)
    pdf.ln(1)

def math_line(pdf, text):
    pdf.set_font('Courier', '', 9)
    pdf.set_x(15)
    pdf.cell(w=0, h=5.5, text=text, new_x="LMARGIN", new_y="NEXT")

def math_line_b(pdf, text):
    pdf.set_font('Courier', 'B', 9)
    pdf.set_x(15)
    pdf.cell(w=0, h=5.5, text=text, new_x="LMARGIN", new_y="NEXT")

# ============================================================
# COVER PAGE
# ============================================================
pdf.add_page()
pdf.ln(40)
pdf.set_font('Helvetica', 'B', 22)
pdf.set_text_color(0, 32, 96)
pdf.cell(0, 12, 'Homework 3 - SSIE 553', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 14)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 8, 'Spring 2026', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, 'Lana Jalal Gidan', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)
pdf.set_font('Helvetica', '', 12)
pdf.cell(0, 8, 'Instructor: Neha Patankar', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 8, 'Due: 02/23/2026', align='C', new_x="LMARGIN", new_y="NEXT")

# ============================================================
# QUESTION 1 [30 pts]
# ============================================================
pdf.add_page()
title_section(pdf, 'Question 1 [30 pts]: Simplex Method Iterations')
body(pdf, 'Given LP:   Min z = -2x1 + x2 - x3')
body(pdf, 'Subject to:\n  x1 - x2 + 3x3 <= 4\n  2x1 + x2 <= 10\n  x1 - x2 - x3 <= 7\n  x1, x2, x3 >= 0')

subtitle(pdf, 'Step 1: Convert to Standard Form')
body(pdf, 'Introduce slack variables x4, x5, x6 >= 0:')
math_line(pdf, '  x1 - x2 + 3x3 + x4           = 4')
math_line(pdf, '  2x1 + x2           + x5       = 10')
math_line(pdf, '  x1 - x2 - x3           + x6   = 7')
pdf.ln(2)
body(pdf, 'The constraint matrix A and RHS vector b are:')
math_line(pdf, '      [ 1  -1   3   1  0  0 ]       [ 4  ]')
math_line(pdf, '  A = [ 2   1   0   0  1  0 ],  b = [ 10 ]')
math_line(pdf, '      [ 1  -1  -1   0  0  1 ]       [ 7  ]')
pdf.ln(2)
body(pdf, 'Cost vector: c = [-2, 1, -1, 0, 0, 0]^T')

# Iteration 0
pdf.ln(3)
subtitle(pdf, 'Iteration k = 0 (Initial BFS)')
body(pdf, 'Initial basic variables are the slack variables. Non-basic variables are set to zero.')
pdf.ln(1)
body_bold(pdf, 'Basic and Non-basic Variables:')
math_line(pdf, '  xB_0 = [x4, x5, x6]^T = [4, 10, 7]^T')
math_line(pdf, '  xN_0 = [x1, x2, x3]^T')
pdf.ln(2)
body_bold(pdf, 'Basis Matrix B_0 and Non-basic Matrix N_0:')
math_line(pdf, '       [ 1  0  0 ]          [ 1  -1   3 ]')
math_line(pdf, '  B0 = [ 0  1  0 ],   N0 =  [ 2   1   0 ]')
math_line(pdf, '       [ 0  0  1 ]          [ 1  -1  -1 ]')
pdf.ln(2)
body_bold(pdf, 'Simplex Multipliers (lambda_0):')
math_line(pdf, '  cB = [0, 0, 0]^T')
math_line(pdf, '  lambda_0 = cB^T * B0^(-1) = [0, 0, 0] * I = [0, 0, 0]')
pdf.ln(2)
body_bold(pdf, 'Reduced Costs (d_0):')
math_line(pdf, '  cN = [-2, 1, -1]^T')
math_line(pdf, '  d_0 = cN - N0^T * lambda_0^T = [-2, 1, -1] - [0, 0, 0] = [-2, 1, -1]')
pdf.ln(2)
body(pdf, 'Since d1 = -2 < 0 (most negative), x1 enters the basis (minimization: enter most negative reduced cost).')
pdf.ln(1)
body_bold(pdf, 'Ratio Test (Minimum Ratio for x1 entering):')
math_line(pdf, '  B0^(-1) * a1 = I * [1, 2, 1]^T = [1, 2, 1]^T')
math_line(pdf, '  Ratios: 4/1 = 4,  10/2 = 5,  7/1 = 7')
math_line(pdf, '  Min ratio = 4 (row 1) => x4 leaves the basis')

# Iteration 1
pdf.add_page()
subtitle(pdf, 'Iteration k = 1 (After First Pivot)')
body(pdf, 'Pivot: x1 enters, x4 leaves. Pivot element = 1 at position (row 1, col 1).')
pdf.ln(1)
body_bold(pdf, 'Computing B1^(-1):')
math_line(pdf, '       [ 1  0  0 ]')
math_line(pdf, '  B1 = [ 2  1  0 ]   (columns of A for x1, x5, x6)')
math_line(pdf, '       [ 1  0  1 ]')
pdf.ln(1)
math_line(pdf, '  Row-reduce [B1 | I]:')
math_line(pdf, '  R2 = R2 - 2*R1:  [0, 1, 0 | -2, 1, 0]')
math_line(pdf, '  R3 = R3 - 1*R1:  [0, 0, 1 | -1, 0, 1]')
pdf.ln(1)
math_line(pdf, '          [  1   0   0 ]')
math_line(pdf, '  B1^-1 = [ -2   1   0 ]')
math_line(pdf, '          [ -1   0   1 ]')
pdf.ln(2)
body_bold(pdf, 'Basic and Non-basic Variables:')
math_line(pdf, '  xB_1 = B1^(-1) * b = [1,0,0; -2,1,0; -1,0,1] * [4; 10; 7]')
math_line(pdf, '       = [4, -8+10, -4+7] = [4, 2, 3]')
math_line(pdf, '  xB_1 = [x1, x5, x6]^T = [4, 2, 3]^T')
math_line(pdf, '  xN_1 = [x4, x2, x3]^T')
pdf.ln(2)
body_bold(pdf, 'Basis Matrix B_1 and Non-basic Matrix N_1:')
math_line(pdf, '       [ 1  0  0 ]          [ 1  -1   3 ]')
math_line(pdf, '  B1 = [ 2  1  0 ],   N1 =  [ 0   1   0 ]')
math_line(pdf, '       [ 1  0  1 ]          [ 0  -1  -1 ]')
pdf.ln(2)
body_bold(pdf, 'Simplex Multipliers (lambda_1):')
math_line(pdf, '  cB = [-2, 0, 0]^T   (costs for x1, x5, x6)')
math_line(pdf, '  lambda_1 = cB^T * B1^(-1)')
math_line(pdf, '           = [-2, 0, 0] * [1,0,0; -2,1,0; -1,0,1]')
math_line(pdf, '           = [-2, 0, 0]')
pdf.ln(2)
body_bold(pdf, 'Reduced Costs (d_1):')
math_line(pdf, '  cN = [0, 1, -1]^T   (costs for x4, x2, x3)')
math_line(pdf, '  lambda_1 * N1 = [-2, 0, 0] * [1,-1,3; 0,1,0; 0,-1,-1]')
math_line(pdf, '                = [-2, 2, -6]')
math_line(pdf, '  d_1 = cN - (lambda_1 * N1)^T = [0,1,-1] - [-2,2,-6] = [2, -1, 5]')
pdf.ln(2)
body(pdf, 'Since d2 = -1 < 0 (for x2), x2 enters the basis.')
pdf.ln(1)
body_bold(pdf, 'Ratio Test (x2 entering):')
math_line(pdf, '  B1^(-1) * a2 = [1,0,0; -2,1,0; -1,0,1] * [-1; 1; -1]')
math_line(pdf, '               = [-1, 3, 0]^T')
math_line(pdf, '  Only positive entry: row 2 (value 3)')
math_line(pdf, '  Ratio: 2/3')
math_line(pdf, '  Min ratio = 2/3 (row 2) => x5 leaves the basis')

# Iteration 2
pdf.add_page()
subtitle(pdf, 'Iteration k = 2 (Optimal Solution)')
body(pdf, 'Pivot: x2 enters, x5 leaves.')
pdf.ln(1)
body_bold(pdf, 'Computing B2^(-1):')
math_line(pdf, '       [ 1  -1  0 ]')
math_line(pdf, '  B2 = [ 2   1  0 ]   (columns of A for x1, x2, x6)')
math_line(pdf, '       [ 1  -1  1 ]')
pdf.ln(1)
math_line(pdf, '  Row-reduce [B2 | I]:')
math_line(pdf, '  R2 = R2 - 2*R1:        [0,  3, 0 | -2, 1, 0]')
math_line(pdf, '  R3 = R3 - R1:          [0,  0, 1 | -1, 0, 1]')
math_line(pdf, '  R2 = R2/3:             [0,  1, 0 | -2/3, 1/3, 0]')
math_line(pdf, '  R1 = R1 + R2:          [1,  0, 0 |  1/3, 1/3, 0]')
pdf.ln(1)
math_line(pdf, '          [ 1/3   1/3   0 ]')
math_line(pdf, '  B2^-1 = [ -2/3  1/3   0 ]')
math_line(pdf, '          [ -1     0    1 ]')
pdf.ln(2)
body_bold(pdf, 'Basic and Non-basic Variables:')
math_line(pdf, '  xB_2 = B2^(-1) * b')
math_line(pdf, '       = [1/3,1/3,0; -2/3,1/3,0; -1,0,1] * [4; 10; 7]')
math_line(pdf, '       = [4/3+10/3, -8/3+10/3, -4+7]')
math_line(pdf, '       = [14/3, 2/3, 3]')
math_line(pdf, '  xB_2 = [x1, x2, x6]^T = [14/3, 2/3, 3]^T')
math_line(pdf, '  xN_2 = [x4, x5, x3]^T')
pdf.ln(2)
body_bold(pdf, 'Basis Matrix B_2 and Non-basic Matrix N_2:')
math_line(pdf, '       [ 1  -1  0 ]          [ 1   0   3 ]')
math_line(pdf, '  B2 = [ 2   1  0 ],   N2 =  [ 0   1   0 ]')
math_line(pdf, '       [ 1  -1  1 ]          [ 0   0  -1 ]')
pdf.ln(2)
body_bold(pdf, 'Simplex Multipliers (lambda_2):')
math_line(pdf, '  cB = [-2, 1, 0]^T   (costs for x1, x2, x6)')
math_line(pdf, '  lambda_2 = cB^T * B2^(-1)')
math_line(pdf, '           = [-2, 1, 0] * [1/3,1/3,0; -2/3,1/3,0; -1,0,1]')
math_line(pdf, '           = [-2/3-2/3, -2/3+1/3, 0]')
math_line(pdf, '           = [-4/3, -1/3, 0]')
pdf.ln(2)
body_bold(pdf, 'Reduced Costs (d_2):')
math_line(pdf, '  cN = [0, 0, -1]^T   (costs for x4, x5, x3)')
math_line(pdf, '  lambda_2 * N2 = [-4/3, -1/3, 0] * [1,0,3; 0,1,0; 0,0,-1]')
math_line(pdf, '                = [-4/3, -1/3, -4]')
math_line(pdf, '  d_2 = cN - (lambda_2 * N2)^T = [0,0,-1] - [-4/3,-1/3,-4]')
math_line(pdf, '      = [4/3, 1/3, 3]')
pdf.ln(2)
body_bold(pdf, 'Optimality Check:')
body(pdf, 'All reduced costs d_2 = [4/3, 1/3, 3] >= 0. For minimization, this means no improvement is possible. The current BFS is OPTIMAL.')
pdf.ln(1)
body_bold(pdf, 'Optimal Solution:')
math_line(pdf, '  x1* = 14/3,  x2* = 2/3,  x3* = 0')
math_line(pdf, '  z*  = -2(14/3) + 1(2/3) - 1(0) = -28/3 + 2/3 = -26/3')

# ============================================================
# QUESTION 2 [25 pts]
# ============================================================
pdf.add_page()
title_section(pdf, 'Question 2 [20+5 pts]: Simplex Method & Alternative Optima')
body(pdf, 'Given LP:   Max z = x1 + x2')
body(pdf, 'Subject to:\n  x1 + x2 + x3 <= 1\n  x1 + 2x3 <= 1/2\n  x1, x2, x3 >= 0')

subtitle(pdf, 'Part (i): Solve using the Simplex Method')
body(pdf, 'Standard form with slack variables x4, x5 >= 0:')
math_line(pdf, '  x1 + x2 + x3 + x4      = 1')
math_line(pdf, '  x1      + 2x3      + x5 = 1/2')
pdf.ln(2)
body_bold(pdf, 'Initial Simplex Tableau:')
math_line(pdf, '  BV  | x1   x2   x3   x4   x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  x4  |  1     1    1    1    0   |  1')
math_line(pdf, '  x5  |  1     0    2    0    1   | 1/2')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  z   | -1    -1    0    0    0   |  0')
pdf.ln(2)
body(pdf, 'For maximization, enter variable with most negative z-row coefficient. Both x1 and x2 have coefficient -1. Choose x1 (leftmost).')
pdf.ln(1)
body_bold(pdf, 'Ratio Test (x1 entering):')
math_line(pdf, '  Row 1: 1/1 = 1')
math_line(pdf, '  Row 2: (1/2)/1 = 1/2   <-- minimum')
math_line(pdf, '  x5 leaves. Pivot element = 1 at (row 2, col 1).')
pdf.ln(2)
body_bold(pdf, 'Pivot Operations:')
math_line(pdf, '  New R2 = R2 (pivot = 1, unchanged)')
math_line(pdf, '  New R1 = R1 - R2:  [0, 1, -1, 1, -1 | 1/2]')
math_line(pdf, '  New z  = z + R2:   [0, -1, 2, 0, 1  | 1/2]')
pdf.ln(2)
body_bold(pdf, 'Tableau After Iteration 1:')
math_line(pdf, '  BV  | x1   x2   x3   x4   x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  x4  |  0     1   -1    1   -1   | 1/2')
math_line(pdf, '  x1  |  1     0    2    0    1   | 1/2')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  z   |  0    -1    2    0    1   | 1/2')
pdf.ln(2)
body(pdf, 'x2 has coefficient -1 (negative). x2 enters.')
pdf.ln(1)
body_bold(pdf, 'Ratio Test (x2 entering):')
math_line(pdf, '  Row 1: coeff = 1 > 0, ratio = (1/2)/1 = 1/2')
math_line(pdf, '  Row 2: coeff = 0, skip')
math_line(pdf, '  x4 leaves. Pivot element = 1 at (row 1, col 2).')
pdf.ln(2)
body_bold(pdf, 'Pivot Operations:')
math_line(pdf, '  New R1 = R1 (pivot = 1, unchanged)')
math_line(pdf, '  New R2 = R2 (coeff of x2 = 0, unchanged)')
math_line(pdf, '  New z  = z + R1:  [0, 0, 1, 1, 0 | 1]')
pdf.ln(2)
body_bold(pdf, 'Tableau After Iteration 2 (Optimal):')
math_line(pdf, '  BV  | x1   x2   x3   x4   x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  x2  |  0     1   -1    1   -1   | 1/2')
math_line(pdf, '  x1  |  1     0    2    0    1   | 1/2')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  z   |  0     0    1    1    0   |  1')
pdf.ln(2)
body(pdf, 'All z-row coefficients >= 0. OPTIMAL for maximization.')
body_bold(pdf, 'Optimal Solution: x1* = 1/2, x2* = 1/2, x3* = 0, z* = 1')

pdf.add_page()
subtitle(pdf, 'Part (ii): Alternative Optimal Solution?')
body(pdf, 'Rule: An alternative optimal solution exists if a NON-BASIC variable has a reduced cost of exactly zero in the optimal tableau.')
pdf.ln(1)
body(pdf, 'Examining the z-row of the optimal tableau:')
math_line(pdf, '  Non-basic variables: x3 (coeff = 1), x4 (coeff = 1), x5 (coeff = 0)')
pdf.ln(1)
body_bold(pdf, 'x5 has a reduced cost of exactly 0. YES, an alternative optimal solution exists.')
pdf.ln(2)
body(pdf, 'To find the alternative extreme point, bring x5 into the basis:')
math_line(pdf, '  Column for x5 in current tableau: [-1, 1]^T')
math_line(pdf, '  Ratio test:')
math_line(pdf, '    Row 1: coeff = -1 (negative, skip)')
math_line(pdf, '    Row 2: coeff = 1, ratio = (1/2)/1 = 1/2')
math_line(pdf, '  x1 leaves. Pivot on (row 2, col 5), pivot = 1.')
pdf.ln(1)
body_bold(pdf, 'Pivot Operations:')
math_line(pdf, '  New R2 = R2: [1, 0, 2, 0, 1 | 1/2]')
math_line(pdf, '  New R1 = R1 + R2: [1, 1, 1, 1, 0 | 1]')
math_line(pdf, '  z-row unchanged (coeff of x5 = 0)')
pdf.ln(1)
body_bold(pdf, 'New Optimal Tableau:')
math_line(pdf, '  BV  | x1   x2   x3   x4   x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  x2  |  1     1    1    1    0   |  1')
math_line(pdf, '  x5  |  1     0    2    0    1   | 1/2')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  z   |  0     0    1    1    0   |  1')
pdf.ln(2)
body_bold(pdf, 'Alternative Optimal Extreme Point:')
math_line(pdf, '  x1* = 0,  x2* = 1,  x3* = 0,  z* = 1')
pdf.ln(1)
body(pdf, 'Both solutions give the same optimal value z* = 1, confirming alternative optima.')

# ============================================================
# QUESTION 3 [25 pts]
# ============================================================
pdf.add_page()
title_section(pdf, 'Question 3 [5+20 pts]: Unbounded LP')
body(pdf, 'Given LP:   Max z = 2x2')
body(pdf, 'Subject to:\n  x1 - x2 <= 4\n  -x1 + x2 <= 1\n  x1, x2 >= 0')

subtitle(pdf, 'Part (i): State the Unboundedness Rule')
body_bold(pdf, 'Unboundedness Rule:')
body(pdf, 'During the simplex method for a maximization problem, if a non-basic variable x_j is selected to enter the basis (because its reduced cost is positive, i.e., c_j - z_j > 0), and ALL entries in the corresponding pivot column are less than or equal to zero (y_ij <= 0 for all rows i), then there is no finite upper bound on how much x_j can increase. Consequently, the objective function z can be increased without bound, and the LP is UNBOUNDED.')

subtitle(pdf, 'Part (ii): Show the LP is Unbounded Using the Rule')
body(pdf, 'Standard form with slack variables x3, x4 >= 0:')
math_line(pdf, '   x1 - x2 + x3      = 4')
math_line(pdf, '  -x1 + x2      + x4 = 1')
pdf.ln(2)
body_bold(pdf, 'Initial Simplex Tableau:')
math_line(pdf, '  BV  | x1   x2   x3   x4  | RHS')
math_line(pdf, '  ----|------|------|------|------|-----')
math_line(pdf, '  x3  |  1    -1    1    0   |  4')
math_line(pdf, '  x4  | -1     1    0    1   |  1')
math_line(pdf, '  ----|------|------|------|------|-----')
math_line(pdf, '  z   |  0    -2    0    0   |  0')
pdf.ln(2)
body(pdf, 'For Max, x2 has z-row coefficient -2 (most negative). x2 enters.')
pdf.ln(1)
body_bold(pdf, 'Ratio Test (x2 entering):')
math_line(pdf, '  Pivot column for x2: [-1, 1]^T')
math_line(pdf, '  Row 1: coeff = -1 (negative, skip)')
math_line(pdf, '  Row 2: coeff = 1, ratio = 1/1 = 1')
math_line(pdf, '  x4 leaves. Pivot element = 1 at (row 2, col 2).')
pdf.ln(2)
body_bold(pdf, 'Pivot Operations:')
math_line(pdf, '  New R2 = R2: [-1, 1, 0, 1 | 1]')
math_line(pdf, '  New R1 = R1 + R2: [0, 0, 1, 1 | 5]')
math_line(pdf, '  New z = z + 2*R2: [-2, 0, 0, 2 | 2]')
pdf.ln(2)
body_bold(pdf, 'Tableau After Iteration 1:')
math_line(pdf, '  BV  | x1   x2   x3   x4  | RHS')
math_line(pdf, '  ----|------|------|------|------|-----')
math_line(pdf, '  x3  |  0     0    1    1   |  5')
math_line(pdf, '  x2  | -1     1    0    1   |  1')
math_line(pdf, '  ----|------|------|------|------|-----')
math_line(pdf, '  z   | -2     0    0    2   |  2')
pdf.ln(2)
body(pdf, 'For Max, x1 has z-row coefficient -2 (negative), so x1 should enter the basis.')
pdf.ln(1)
body_bold(pdf, 'Check the Pivot Column for x1:')
math_line(pdf, '  Column for x1: [0, -1]^T')
pdf.ln(1)
body_bold(pdf, 'Applying the Unboundedness Rule:')
body(pdf, 'ALL entries in the x1 column are <= 0:')
math_line(pdf, '  Row 1: 0  <= 0  (zero)')
math_line(pdf, '  Row 2: -1 <= 0  (negative)')
pdf.ln(1)
body(pdf, 'Since we want to bring x1 into the basis (it would improve the objective), but ALL entries in the pivot column are non-positive, there is no valid pivot. We can increase x1 without limit, and since x1 has a negative coefficient in the z-row (-2), the objective z will increase without bound.')
pdf.ln(2)
body_bold(pdf, 'Conclusion: This LP is UNBOUNDED. The objective function z = 2x2 can be made arbitrarily large.')

# ============================================================
# QUESTION 4 [20 pts]
# ============================================================
pdf.add_page()
title_section(pdf, 'Question 4 [10+5+5 pts]: Degeneracy in LP')
body(pdf, 'Given LP:   Max z = 5x1 + 3x2')
body(pdf, 'Subject to:\n  4x1 + 2x2 <= 12\n  4x1 + x2 <= 10\n  x1 + x2 <= 4\n  x1, x2 >= 0')

subtitle(pdf, 'Part (i): Solve Using Simplex Until Degenerate BFS')
body(pdf, 'Standard form with slack variables x3, x4, x5 >= 0:')
math_line(pdf, '  4x1 + 2x2 + x3           = 12')
math_line(pdf, '  4x1 + x2       + x4       = 10')
math_line(pdf, '   x1 + x2            + x5  = 4')
pdf.ln(2)
body_bold(pdf, 'Initial Tableau (Iteration 0):')
math_line(pdf, '  BV  | x1   x2   x3   x4   x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  x3  |  4     2    1    0    0   |  12')
math_line(pdf, '  x4  |  4     1    0    1    0   |  10')
math_line(pdf, '  x5  |  1     1    0    0    1   |  4')
math_line(pdf, '  ----|------|------|------|------|------|-----')
math_line(pdf, '  z   | -5    -3    0    0    0   |  0')
pdf.ln(2)
body(pdf, 'Most negative z-row coefficient: x1 (-5). x1 enters.')
body_bold(pdf, 'Ratio Test:')
math_line(pdf, '  Row 1: 12/4 = 3')
math_line(pdf, '  Row 2: 10/4 = 2.5  <-- minimum')
math_line(pdf, '  Row 3: 4/1  = 4')
math_line(pdf, '  x4 leaves. Pivot at (row 2, col 1), pivot = 4.')
pdf.ln(2)
body_bold(pdf, 'Pivot Operations:')
math_line(pdf, '  New R2 = R2/4:     [1, 1/4, 0, 1/4, 0  | 5/2]')
math_line(pdf, '  New R1 = R1-4*R2:  [0, 1,   1, -1,  0  | 2]')
math_line(pdf, '  New R3 = R3-1*R2:  [0, 3/4, 0, -1/4, 1 | 3/2]')
math_line(pdf, '  New z  = z+5*R2:   [0, -7/4, 0, 5/4, 0 | 25/2]')
pdf.ln(2)
body_bold(pdf, 'Tableau After Iteration 1:')
math_line(pdf, '  BV  | x1    x2    x3    x4    x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|------')
math_line(pdf, '  x3  |  0     1     1    -1     0   |  2')
math_line(pdf, '  x1  |  1    1/4    0    1/4    0   | 5/2')
math_line(pdf, '  x5  |  0    3/4    0   -1/4    1   | 3/2')
math_line(pdf, '  ----|------|------|------|------|------|------')
math_line(pdf, '  z   |  0   -7/4    0    5/4    0   | 25/2')
pdf.ln(2)
body(pdf, 'x2 has z-row coefficient -7/4 (negative). x2 enters.')
body_bold(pdf, 'Ratio Test:')
math_line(pdf, '  Row 1: 2/1   = 2')
math_line(pdf, '  Row 2: (5/2)/(1/4) = 10')
math_line(pdf, '  Row 3: (3/2)/(3/4) = 2    <-- TIE!')
math_line(pdf, '  Tie between Row 1 and Row 3 (both ratio = 2)')
math_line(pdf, '  => This TIE signals DEGENERACY!')
math_line(pdf, '  Choose Row 1: x3 leaves.')
pdf.ln(2)

pdf.add_page()
body_bold(pdf, 'Pivot Operations (x2 enters, x3 leaves):')
math_line(pdf, '  Pivot element = 1 at (row 1, col 2)')
math_line(pdf, '  New R1 = R1:           [0, 1,    1,   -1,    0  | 2]')
math_line(pdf, '  New R2 = R2-(1/4)*R1:  [1, 0, -1/4,  1/2,   0  | 2]')
math_line(pdf, '  New R3 = R3-(3/4)*R1:  [0, 0, -3/4,  1/2,   1  | 0]')
math_line(pdf, '  New z  = z+(7/4)*R1:   [0, 0,  7/4, -3/4,   0  | 16]')
pdf.ln(2)
body_bold(pdf, 'Tableau After Iteration 2 (Degenerate BFS):')
math_line(pdf, '  BV  | x1    x2    x3     x4    x5  | RHS')
math_line(pdf, '  ----|------|------|------|------|------|------')
math_line(pdf, '  x2  |  0     1     1     -1     0   |  2')
math_line(pdf, '  x1  |  1     0   -1/4    1/2    0   |  2')
math_line(pdf, '  x5  |  0     0   -3/4    1/2    1   |  0')
math_line(pdf, '  ----|------|------|------|------|------|------')
math_line(pdf, '  z   |  0     0    7/4   -3/4    0   | 16')
pdf.ln(2)
body_bold(pdf, 'Degenerate BFS Confirmed:')
body(pdf, 'The basic variable x5 = 0 in the basis. A BFS is degenerate when one or more basic variables equal zero. This occurred because of the tie in the ratio test at Iteration 1.')
pdf.ln(1)
body_bold(pdf, 'Current BFS: x1 = 2, x2 = 2, x3 = 0, x4 = 0, x5 = 0, z = 16')
body(pdf, 'Note: x4 has z-row coefficient -3/4 (negative), so this is not yet optimal. However, the question only asks us to solve until we confirm degeneracy, which we have done.')

# Part ii
pdf.ln(4)
subtitle(pdf, 'Part (ii): Graph the Feasible Region')
body(pdf, 'At the degenerate BFS (x1, x2) = (2, 2), we check which constraints are binding:')
math_line(pdf, '  Constraint 1: 4(2) + 2(2) = 12 = 12  => BINDING')
math_line(pdf, '  Constraint 2: 4(2) + 1(2) = 10 = 10  => BINDING')
math_line(pdf, '  Constraint 3: 1(2) + 1(2) = 4  = 4   => BINDING')
pdf.ln(1)
body_bold(pdf, 'All THREE original constraints are binding at the point (2, 2).')
body(pdf, 'This is the geometric signature of degeneracy: more constraints meet at this vertex than needed to define it (only 2 are needed in 2D).')
pdf.ln(1)
body(pdf, 'In standard form, the binding constraints correspond to the non-negativity constraints x3 >= 0, x4 >= 0, and x5 >= 0 all being active (all three equal zero). See the graph below:')

if pdf.get_y() + 90 > pdf.h - 20:
    pdf.add_page()
pdf.image('q4_graph.png', x=15, y=pdf.get_y() + 2, w=170)

# Part iii
pdf.add_page()
subtitle(pdf, 'Part (iii): Are Binding Constraints Greater Than n?')
body(pdf, 'In standard form Ax = b, x >= 0, the key quantities are:')
math_line(pdf, '  n = 5 (total variables: x1, x2, x3, x4, x5)')
math_line(pdf, '  m = 3 (number of equality constraints)')
pdf.ln(1)
body(pdf, 'Count of binding constraints at the degenerate BFS (x1=2, x2=2, x3=0, x4=0, x5=0):')
math_line(pdf, '  - 3 equality constraints (Ax = b): always binding')
math_line(pdf, '  - 3 non-negativity constraints binding: x3=0, x4=0, x5=0')
math_line(pdf, '  Total binding constraints = 3 + 3 = 6')
pdf.ln(1)
body_bold(pdf, 'Is 6 > n = 5?  YES!')
pdf.ln(1)
body(pdf, 'The number of binding constraints (6) exceeds the number of variables n = 5. For a non-degenerate BFS, exactly n = 5 constraints should be binding (m = 3 equality constraints + exactly n - m = 2 active non-negativity constraints). Here we have 3 active non-negativity constraints instead of 2, which is the algebraic definition of degeneracy.')

pdf.output('SSIE553_Homework3_Lana_Jalal_Gidan.pdf')
print("PDF generated: SSIE553_Homework3_Lana_Jalal_Gidan.pdf")

if os.path.exists('q4_graph.png'):
    os.remove('q4_graph.png')
    print("Cleaned up temporary graph file")
