import matplotlib
matplotlib.use('Agg')
from fpdf import FPDF
import numpy as np

class PDF(FPDF):
    def header(self):
        pass
    def footer(self):
        self.set_y(-15)
        self.set_font('Times', 'I', 10)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

pdf = PDF('P', 'mm', 'Letter')
pdf.set_auto_page_break(auto=True, margin=20)
pdf.set_left_margin(20)
pdf.set_right_margin(20)

W = 215.9 - 20 - 20
LH = 5.5
INDENT = 8

def title_text(pdf, text):
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, LH, text, align='C', new_x="LMARGIN", new_y="NEXT")

def heading(pdf, text):
    pdf.ln(2)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, LH, text, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

def subheading(pdf, text):
    pdf.ln(1)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, LH, text, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

def body(pdf, text):
    pdf.set_font('Times', '', 12)
    pdf.multi_cell(0, LH, text)
    pdf.ln(0.5)

def body_bold(pdf, text):
    pdf.set_font('Times', 'B', 12)
    pdf.multi_cell(0, LH, text)
    pdf.ln(0.5)

def math(pdf, text):
    pdf.set_font('Courier', '', 11)
    pdf.multi_cell(0, LH, text)
    pdf.ln(0.5)

def math_indent(pdf, text):
    pdf.set_font('Courier', '', 11)
    lm = pdf.l_margin
    pdf.set_left_margin(lm + INDENT)
    pdf.set_x(lm + INDENT)
    pdf.multi_cell(0, LH, text)
    pdf.set_left_margin(lm)
    pdf.ln(0.3)

def step(pdf, text):
    pdf.set_font('Times', 'B', 12)
    pdf.multi_cell(0, LH, text)
    pdf.ln(0.5)

def bullet(pdf, text):
    pdf.set_font('Times', '', 12)
    lm = pdf.l_margin
    pdf.set_left_margin(lm + INDENT)
    pdf.set_x(lm + INDENT)
    pdf.multi_cell(0, LH, f'- {text}')
    pdf.set_left_margin(lm)

def tbl(pdf, text):
    pdf.set_font('Courier', '', 9)
    pdf.cell(0, LH, text, new_x="LMARGIN", new_y="NEXT")

# ============================================================
# COVER PAGE
# ============================================================
pdf.add_page()
pdf.ln(40)
title_text(pdf, 'SSIE 553 - Homework 4')
pdf.ln(LH)
title_text(pdf, 'Spring 2026')
pdf.ln(LH)
title_text(pdf, 'Professor Neha Patankar')
pdf.ln(LH * 4)
title_text(pdf, 'Lana Jalal Gidan')
pdf.ln(LH)
pdf.set_font('Times', '', 12)
pdf.cell(0, LH, 'Watson College of Engineering and Applied Science', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, LH, 'Binghamton University', align='C', new_x="LMARGIN", new_y="NEXT")
pdf.ln(LH * 2)
pdf.cell(0, LH, 'March 2, 2026', align='C', new_x="LMARGIN", new_y="NEXT")

# ============================================================
# QUESTION 1
# ============================================================
pdf.add_page()
heading(pdf, 'Question 1')
body(pdf, 'Given the LP:')
math_indent(pdf, 'Max z = -x1 + x2')
math_indent(pdf, 'Subject to:')
math_indent(pdf, '2x1 + x2 + s1 = 4   ... (1)')
math_indent(pdf, ' x1 + x2 + s2 = 2   ... (2)')
math_indent(pdf, 'x1, x2, s1, s2 >= 0')
body(pdf, 'where s1 and s2 are slack variables. The basic variables are x2 and s1.')

subheading(pdf, 'Part (i): Determine xB, xN, B, N, cB, cN, and b')
body(pdf, 'We have four variables: x1, x2, s1, s2. The basic variables (BV) are x2 and s1. The non-basic variables (NBV) are x1 and s2.')

step(pdf, 'Basic and Non-Basic Variable Vectors:')
math_indent(pdf, 'xB = [x2, s1]^T')
math_indent(pdf, 'xN = [x1, s2]^T')

step(pdf, 'Basis Matrix B (columns of basic variables from the constraint matrix):')
body(pdf, 'From the constraints in standard form:')
math_indent(pdf, 'Constraint 1: 2x1 + x2 + s1 = 4')
math_indent(pdf, 'Constraint 2:  x1 + x2 + s2 = 2')
body(pdf, 'The column of x2 is [1, 1]^T and the column of s1 is [1, 0]^T.')
math_indent(pdf, '     | x2  s1 |   | 1  1 |')
math_indent(pdf, 'B =  |        | = |       |')
math_indent(pdf, '     | x2  s1 |   | 1  0 |')

step(pdf, 'Non-Basis Matrix N (columns of non-basic variables):')
body(pdf, 'The column of x1 is [2, 1]^T and the column of s2 is [0, 1]^T.')
math_indent(pdf, '     | x1  s2 |   | 2  0 |')
math_indent(pdf, 'N =  |        | = |       |')
math_indent(pdf, '     | x1  s2 |   | 1  1 |')

step(pdf, 'Objective Function Coefficients:')
body(pdf, 'From z = -x1 + x2 + 0*s1 + 0*s2:')
math_indent(pdf, 'cB = [c_x2, c_s1]^T = [1, 0]^T')
math_indent(pdf, 'cN = [c_x1, c_s2]^T = [-1, 0]^T')

step(pdf, 'Right-Hand Side Vector b:')
math_indent(pdf, 'b = [4, 2]^T')

subheading(pdf, 'Part (ii): Construct the Simplex Tableau')
body(pdf, 'To construct the simplex tableau for the given basis, we need B^(-1), then compute B^(-1)*N, B^(-1)*b, and the reduced costs.')

step(pdf, 'Step 1: Compute B^(-1)')
math_indent(pdf, '     | 1  1 |')
math_indent(pdf, 'B =  |      |')
math_indent(pdf, '     | 1  0 |')
body(pdf, 'det(B) = (1)(0) - (1)(1) = -1')
math_indent(pdf, '         |  0  -1 |     | 0  1 |')
math_indent(pdf, 'B^(-1) = |        | / (-1) = |      |')
math_indent(pdf, '         | -1   1 |     | 1 -1 |')

step(pdf, 'Step 2: Compute B^(-1) * b (basic variable values)')
math_indent(pdf, '              | 0  1 | | 4 |   | 2 |')
math_indent(pdf, 'B^(-1) * b = |      | |   | = |   |')
math_indent(pdf, '              | 1 -1 | | 2 |   | 2 |')
body(pdf, 'So x2 = 2 and s1 = 2.')

step(pdf, 'Step 3: Compute B^(-1) * N')
math_indent(pdf, '               | 0  1 | | 2  0 |   | 1  1 |')
math_indent(pdf, 'B^(-1) * N =  |      | |      | = |      |')
math_indent(pdf, '               | 1 -1 | | 1  1 |   | 1 -1 |')

step(pdf, 'Step 4: Compute the reduced costs for non-basic variables')
body(pdf, 'Reduced cost = cN^T - cB^T * B^(-1) * N')
math_indent(pdf, 'cB^T * B^(-1) * N = [1, 0] * | 1  1 | = [1, 1]')
math_indent(pdf, '                              | 1 -1 |')
math_indent(pdf, 'Reduced costs = cN^T - cB^T * B^(-1) * N')
math_indent(pdf, '              = [-1, 0] - [1, 1] = [-2, -1]')

step(pdf, 'Step 5: Compute z-value')
math_indent(pdf, 'z = cB^T * B^(-1) * b = [1, 0] * [2, 2]^T = 2')

step(pdf, 'The Simplex Tableau:')
body(pdf, 'Setting xN = 0 (non-basic variables at zero):')

tbl(pdf, '  BV  |  x1   x2   s1   s2  | RHS')
tbl(pdf, ' -----|----------------------|-----')
tbl(pdf, '  x2  |   1    1    0    1   |  2')
tbl(pdf, '  s1  |   1    0    1   -1   |  2')
tbl(pdf, ' -----|----------------------|-----')
tbl(pdf, '   z  |  -2    0    0   -1   |  2')
pdf.ln(1)
body(pdf, 'Note: The z-row shows the reduced costs (coefficients in the z-row for each variable). A negative reduced cost means increasing that variable would decrease z.')

subheading(pdf, 'Part (iii): Comment on Feasibility and Optimality')

step(pdf, 'Feasibility:')
body(pdf, 'A basis is feasible if B^(-1)*b >= 0 (all basic variable values are non-negative).')
math_indent(pdf, 'B^(-1)*b = [2, 2]^T')
body(pdf, 'Both values are non-negative (x2 = 2 >= 0 and s1 = 2 >= 0), so the basis IS FEASIBLE.')

step(pdf, 'Optimality:')
body(pdf, 'For a maximization problem, a feasible basis is optimal if all reduced costs of non-basic variables are <= 0.')
math_indent(pdf, 'Reduced cost of x1 = -2 <= 0  (OK)')
math_indent(pdf, 'Reduced cost of s2 = -1 <= 0  (OK)')
body(pdf, 'All reduced costs are non-positive, so the basis IS OPTIMAL.')

step(pdf, 'Conclusion:')
body(pdf, 'The given basis {x2, s1} is both feasible and optimal. The optimal solution is x1 = 0, x2 = 2, s1 = 2, s2 = 0, with optimal objective value z = 2.')

# ============================================================
# QUESTION 2
# ============================================================
pdf.add_page()
heading(pdf, 'Question 2')
body(pdf, 'Given the LP:')
math_indent(pdf, 'Max z = 3x1 + 7x2 + 5x3')
math_indent(pdf, 'Subject to:')
math_indent(pdf, 'x1 + x2 + x3 <= 50   (Sugar)')
math_indent(pdf, '2x1 + 3x2 + x3 <= 100 (Chocolate)')
math_indent(pdf, 'xi >= 0')
body(pdf, 'Optimal basic variables: {x3, x2}. Non-basic variables: {x1, s1, s2}.')
body(pdf, 'Given:')
math_indent(pdf, '         |  3/2  -1/2 |')
math_indent(pdf, 'B^(-1) = |            |')
math_indent(pdf, '         | -1/2   1/2 |')

step(pdf, 'First, let us identify B and compute key quantities.')
body(pdf, 'The constraint matrix in standard form (with slacks s1, s2):')
math_indent(pdf, 'x1 + x2 + x3 + s1 = 50')
math_indent(pdf, '2x1 + 3x2 + x3 + s2 = 100')
body(pdf, 'Basic variables are {x3, x2}, so:')
math_indent(pdf, '     | x3  x2 |   | 1  1 |')
math_indent(pdf, 'B =  |        | = |      |')
math_indent(pdf, '     | x3  x2 |   | 1  3 |')

step(pdf, 'Compute B^(-1) * b (optimal basic variable values):')
math_indent(pdf, '              |  3/2  -1/2 | | 50  |')
math_indent(pdf, 'B^(-1) * b = |            | |     |')
math_indent(pdf, '              | -1/2   1/2 | | 100 |')
pdf.ln(0.5)
math_indent(pdf, 'x3 = (3/2)(50) + (-1/2)(100) = 75 - 50 = 25')
math_indent(pdf, 'x2 = (-1/2)(50) + (1/2)(100) = -25 + 50 = 25')
body(pdf, 'So the optimal solution is x1 = 0, x2 = 25, x3 = 25.')
math_indent(pdf, 'z = 3(0) + 7(25) + 5(25) = 0 + 175 + 125 = 300')

step(pdf, 'Compute cB^T * B^(-1) (shadow prices / dual variables):')
math_indent(pdf, 'cB = [c_x3, c_x2] = [5, 7]')
math_indent(pdf, 'cB^T * B^(-1) = [5, 7] * | 3/2  -1/2 |')
math_indent(pdf, '                          | -1/2   1/2 |')
math_indent(pdf, '= [5(3/2)+7(-1/2), 5(-1/2)+7(1/2)]')
math_indent(pdf, '= [15/2-7/2, -5/2+7/2]')
math_indent(pdf, '= [4, 1]')
body(pdf, 'So y1 = 4 (shadow price for sugar) and y2 = 1 (shadow price for chocolate).')

subheading(pdf, 'Part (i): Range of c1 (Type 1 candy bar profit)')
body(pdf, 'For the current basis to remain optimal, the reduced cost of x1 (a non-basic variable) must remain <= 0 (for maximization).')
step(pdf, 'Reduced cost of x1:')
math_indent(pdf, 'r1 = c1 - cB^T * B^(-1) * a1')
body(pdf, 'where a1 is the column of x1 in the constraint matrix: a1 = [1, 2]^T.')
math_indent(pdf, 'cB^T * B^(-1) * a1 = [4, 1] * [1, 2]^T')
math_indent(pdf, '                   = 4(1) + 1(2) = 6')
math_indent(pdf, 'r1 = c1 - 6')
body(pdf, 'For optimality: r1 <= 0')
math_indent(pdf, 'c1 - 6 <= 0')
math_indent(pdf, 'c1 <= 6')
body(pdf, 'The current basis remains optimal for c1 <= 6 (i.e., -infinity < c1 <= 6).')

step(pdf, 'If c1 = 7:')
body(pdf, 'Since 7 > 6, the current basis is no longer optimal. We need to pivot x1 into the basis.')
body(pdf, 'Compute B^(-1) * a1:')
math_indent(pdf, '               |  3/2  -1/2 | | 1 |   |  1/2 |')
math_indent(pdf, 'B^(-1) * a1 = |            | |   | = |      |')
math_indent(pdf, '               | -1/2   1/2 | | 2 |   |  1/2 |')
body(pdf, 'The updated column for x1 is [1/2, 1/2]^T. Both entries are positive.')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 'x3 row: 25 / (1/2) = 50')
math_indent(pdf, 'x2 row: 25 / (1/2) = 50')
body(pdf, 'Tie - we can choose either. Let x3 leave (first row). x1 enters, x3 leaves.')
body(pdf, 'Pivot element = 1/2. Multiply row 1 by 2:')
math_indent(pdf, 'New row 1 (x1 row): [1, 1, ...] with x1=50 (after pivoting)')
body(pdf, 'Actually, let us perform this more carefully using the updated tableau.')

step(pdf, 'New BFS after pivoting (x1 enters for x3):')
body(pdf, 'New basis: {x1, x2}')
math_indent(pdf, '         | 1  1 |')
math_indent(pdf, 'B_new =  |      |')
math_indent(pdf, '         | 2  3 |')
math_indent(pdf, 'det(B_new) = 3 - 2 = 1')
math_indent(pdf, '             |  3  -1 |')
math_indent(pdf, 'B_new^(-1) = |        |')
math_indent(pdf, '             | -2   1 |')
math_indent(pdf, '                    |  3  -1 | | 50  |   | 50  |')
math_indent(pdf, 'B_new^(-1) * b =   |        | |     | = |     |')
math_indent(pdf, '                    | -2   1 | | 100 |   |  0  |')
body(pdf, 'So x1 = 50, x2 = 0, x3 = 0.')
math_indent(pdf, 'z = 7(50) + 7(0) + 5(0) = 350')
body(pdf, 'The new optimal solution when c1 = 7 is: x1 = 50, x2 = 0, x3 = 0, z = 350.')

subheading(pdf, 'Part (ii): Range of c2 (Type 2 candy bar profit)')
body(pdf, 'x2 is a basic variable. Changing c2 affects the reduced costs of ALL non-basic variables. We need all reduced costs of non-basic variables to remain <= 0.')

step(pdf, 'With c2 changed to c2_new, cB becomes [5, c2_new]:')
math_indent(pdf, 'cB^T * B^(-1) = [5, c2_new] * | 3/2  -1/2 |')
math_indent(pdf, '                               | -1/2   1/2 |')
math_indent(pdf, '= [5(3/2)+c2(-1/2), 5(-1/2)+c2(1/2)]')
math_indent(pdf, '= [(15-c2)/2, (c2-5)/2]')

step(pdf, 'Reduced cost of x1 (non-basic):')
math_indent(pdf, 'r1 = c1 - cB^T * B^(-1) * a1')
math_indent(pdf, '   = 3 - [(15-c2)/2, (c2-5)/2] * [1, 2]^T')
math_indent(pdf, '   = 3 - [(15-c2)/2 + 2(c2-5)/2]')
math_indent(pdf, '   = 3 - [(15-c2+2c2-10)/2]')
math_indent(pdf, '   = 3 - [(5+c2)/2]')
math_indent(pdf, '   = (6-5-c2)/2 = (1-c2)/2')
body(pdf, 'For optimality: r1 <= 0 => (1-c2)/2 <= 0 => c2 >= 1')

step(pdf, 'Reduced cost of s1 (non-basic):')
body(pdf, 'Column of s1 in constraint matrix: a_s1 = [1, 0]^T.')
math_indent(pdf, 'r_s1 = 0 - [(15-c2)/2, (c2-5)/2] * [1, 0]^T')
math_indent(pdf, '     = -(15-c2)/2 = (c2-15)/2')
body(pdf, 'For optimality: r_s1 <= 0 => (c2-15)/2 <= 0 => c2 <= 15')

step(pdf, 'Reduced cost of s2 (non-basic):')
body(pdf, 'Column of s2: a_s2 = [0, 1]^T.')
math_indent(pdf, 'r_s2 = 0 - [(15-c2)/2, (c2-5)/2] * [0, 1]^T')
math_indent(pdf, '     = -(c2-5)/2 = (5-c2)/2')
body(pdf, 'For optimality: r_s2 <= 0 => (5-c2)/2 <= 0 => c2 >= 5')

step(pdf, 'Combined range:')
math_indent(pdf, 'c2 >= 1, c2 <= 15, c2 >= 5')
math_indent(pdf, '=> 5 <= c2 <= 15')
body(pdf, 'The current basis remains optimal for 5 <= c2 <= 15.')

step(pdf, 'If c2 = 19:')
body(pdf, 'Since 19 > 15, the constraint r_s1 <= 0 is violated. s1 enters the basis.')
body(pdf, 'Compute B^(-1) * a_s1:')
math_indent(pdf, '                |  3/2  -1/2 | | 1 |   |  3/2 |')
math_indent(pdf, 'B^(-1)*a_s1 =  |            | |   | = |      |')
math_indent(pdf, '                | -1/2   1/2 | | 0 |   | -1/2 |')
body(pdf, 'Only the first entry (3/2) is positive. Minimum ratio test:')
math_indent(pdf, 'x3 row: 25 / (3/2) = 50/3 = 16.67')
math_indent(pdf, 'x2 row: 25 / (-1/2) -> negative, skip')
body(pdf, 'x3 leaves. s1 enters. New basis: {s1, x2}.')
math_indent(pdf, '         | 1  1 |           | 3   -1 |')
math_indent(pdf, 'B_new =  |      |, B_new^(-1) = (1/2)|        |')
math_indent(pdf, '         | 0  3 |           | 0    1 |')

body(pdf, 'Wait - let me recalculate. New basis {s1, x2}:')
math_indent(pdf, '         | s1  x2 |   | 1  1 |')
math_indent(pdf, 'B_new =  |        | = |      |')
math_indent(pdf, '         | s2  x2 |   | 0  3 |')
math_indent(pdf, 'det(B_new) = 3 - 0 = 3')
math_indent(pdf, '               | 3  -1 |       | 1   -1/3 |')
math_indent(pdf, 'B_new^(-1) = (1/3)|        | = |          |')
math_indent(pdf, '               | 0   1 |       | 0    1/3 |')
math_indent(pdf, '                    | 1  -1/3 | | 50  |')
math_indent(pdf, 'B_new^(-1) * b =   |         | |     |')
math_indent(pdf, '                    | 0   1/3 | | 100 |')
math_indent(pdf, '= [50-100/3, 100/3] = [50/3, 100/3]')
body(pdf, 'So s1 = 50/3, x2 = 100/3, x1 = 0, x3 = 0.')
math_indent(pdf, 'z = 3(0) + 19(100/3) + 5(0) = 1900/3 = 633.33')
body(pdf, 'The new optimal solution when c2 = 19 is: x1 = 0, x2 = 100/3, x3 = 0, z = 1900/3.')

subheading(pdf, 'Part (iii): Range of b1 (Sugar capacity)')
body(pdf, 'For the current basis to remain feasible (and thus optimal since reduced costs do not depend on b), we need B^(-1)*b_new >= 0.')
step(pdf, 'Let b1 change to b1_new:')
math_indent(pdf, '                  |  3/2  -1/2 | | b1_new |')
math_indent(pdf, 'B^(-1) * b_new = |            | |        |')
math_indent(pdf, '                  | -1/2   1/2 | |  100   |')
math_indent(pdf, 'x3 = (3/2)*b1_new - 50')
math_indent(pdf, 'x2 = (-1/2)*b1_new + 50')
body(pdf, 'For feasibility:')
math_indent(pdf, 'x3 >= 0: (3/2)*b1_new - 50 >= 0 => b1_new >= 100/3')
math_indent(pdf, 'x2 >= 0: (-1/2)*b1_new + 50 >= 0 => b1_new <= 100')
body(pdf, 'The current basis remains optimal for 100/3 <= b1 <= 100 (approximately 33.33 <= b1 <= 100).')

step(pdf, 'If b1 = 60 (60 oz of sugar available):')
body(pdf, 'Since 100/3 <= 60 <= 100, the current basis remains feasible and optimal.')
math_indent(pdf, 'x3 = (3/2)(60) - 50 = 90 - 50 = 40')
math_indent(pdf, 'x2 = (-1/2)(60) + 50 = -30 + 50 = 20')
math_indent(pdf, 'x1 = 0')
math_indent(pdf, 'z = 3(0) + 7(20) + 5(40) = 0 + 140 + 200 = 340')
body(pdf, 'With 60 oz of sugar: make 0 Type 1, 20 Type 2, and 40 Type 3 candy bars. Optimal profit = 340 cents.')

# ============================================================
# QUESTION 3
# ============================================================
pdf.add_page()
heading(pdf, 'Question 3')
body(pdf, 'Given the LP:')
math_indent(pdf, 'Max z = 60x1 + 30x2 + 20x3')
math_indent(pdf, 'Subject to:')
math_indent(pdf, '8x1 + 6x2 + x3 + s1 = 48     ... (6)')
math_indent(pdf, '4x1 + 2x2 + 1.5x3 + s2 = 20  ... (7)')
math_indent(pdf, '2x1 + 1.5x2 + 0.5x3 + s3 = 8 ... (8)')
math_indent(pdf, 'xi, si >= 0')
body(pdf, 'Optimal basic variables: {s1, x3, x1}. Non-basic: {x2, s2, s3}.')
body(pdf, 'Given:')
math_indent(pdf, '         |  1    2    -8  |')
math_indent(pdf, 'B^(-1) = |  0    2    -4  |')
math_indent(pdf, '         |  0   -0.5   1.5|')

step(pdf, 'Compute B^(-1) * b:')
math_indent(pdf, '              | 1    2   -8  | | 48 |')
math_indent(pdf, 'B^(-1) * b = | 0    2   -4  | | 20 |')
math_indent(pdf, '              | 0  -0.5  1.5 | |  8 |')
math_indent(pdf, 's1 = 48 + 2(20) - 8(8) = 48+40-64 = 24')
math_indent(pdf, 'x3 = 0 + 2(20) - 4(8) = 40-32 = 8')
math_indent(pdf, 'x1 = 0 - 0.5(20) + 1.5(8) = -10+12 = 2')
body(pdf, 'So: s1 = 24, x3 = 8, x1 = 2, x2 = 0, s2 = 0, s3 = 0.')
math_indent(pdf, 'z = 60(2) + 30(0) + 20(8) = 120 + 0 + 160 = 280')

step(pdf, 'Compute cB^T * B^(-1) (shadow prices):')
math_indent(pdf, 'cB = [c_s1, c_x3, c_x1] = [0, 20, 60]')
math_indent(pdf, 'cB^T * B^(-1) = [0, 20, 60] * | 1    2   -8  |')
math_indent(pdf, '                               | 0    2   -4  |')
math_indent(pdf, '                               | 0  -0.5  1.5 |')
math_indent(pdf, '= [0, 0+40-30, 0-80+90]')
math_indent(pdf, '= [0, 10, 10]')
body(pdf, 'Shadow prices: y1 = 0, y2 = 10, y3 = 10.')

subheading(pdf, 'Part (i): Range of c3 for current basis to remain optimal')
body(pdf, 'x3 is a basic variable. Changing c3 affects the reduced costs of all non-basic variables. With c3 changed, cB = [0, c3, 60].')

step(pdf, 'New cB^T * B^(-1):')
math_indent(pdf, '[0, c3, 60] * | 1    2    -8  |')
math_indent(pdf, '              | 0    2    -4  |')
math_indent(pdf, '              | 0  -0.5   1.5 |')
math_indent(pdf, '= [0, 2c3-30, -4c3+90]')

step(pdf, 'Reduced cost of x2 (non-basic):')
body(pdf, 'Column of x2: a2 = [6, 2, 1.5]^T')
math_indent(pdf, 'r2 = c2 - cB^T*B^(-1)*a2')
math_indent(pdf, '   = 30 - [0, 2c3-30, -4c3+90]*[6, 2, 1.5]^T')
math_indent(pdf, '   = 30 - [0 + 2(2c3-30) + 1.5(-4c3+90)]')
math_indent(pdf, '   = 30 - [4c3-60-6c3+135]')
math_indent(pdf, '   = 30 - [-2c3+75]')
math_indent(pdf, '   = 30 + 2c3 - 75 = 2c3 - 45')
body(pdf, 'For optimality: r2 <= 0 => 2c3 - 45 <= 0 => c3 <= 22.5')

step(pdf, 'Reduced cost of s2 (non-basic):')
body(pdf, 'Column of s2: a_s2 = [0, 1, 0]^T')
math_indent(pdf, 'r_s2 = 0 - [0, 2c3-30, -4c3+90]*[0, 1, 0]^T')
math_indent(pdf, '     = -(2c3-30) = 30-2c3')
body(pdf, 'For optimality: r_s2 <= 0 => 30-2c3 <= 0 => c3 >= 15')

step(pdf, 'Reduced cost of s3 (non-basic):')
body(pdf, 'Column of s3: a_s3 = [0, 0, 1]^T')
math_indent(pdf, 'r_s3 = 0 - [0, 2c3-30, -4c3+90]*[0, 0, 1]^T')
math_indent(pdf, '     = -(-4c3+90) = 4c3-90')
body(pdf, 'For optimality: r_s3 <= 0 => 4c3-90 <= 0 => c3 <= 22.5')

step(pdf, 'Combined range:')
math_indent(pdf, 'c3 <= 22.5, c3 >= 15, c3 <= 22.5')
math_indent(pdf, '=> 15 <= c3 <= 22.5')

subheading(pdf, 'Part (ii): If c3 = 21, find the new optimal solution')
body(pdf, 'Since 15 <= 21 <= 22.5, the current basis remains optimal. The BFS does not change (only the objective value changes).')
math_indent(pdf, 'x1 = 2, x2 = 0, x3 = 8')
math_indent(pdf, 'z = 60(2) + 30(0) + 21(8) = 120 + 0 + 168 = 288')
body(pdf, 'The new optimal solution is x1 = 2, x2 = 0, x3 = 8 with z = 288.')

subheading(pdf, 'Part (iii): If c3 = 25, find the new optimal solution')
body(pdf, 'Since 25 > 22.5, the current basis is no longer optimal. The reduced cost of x2 becomes:')
math_indent(pdf, 'r2 = 2(25) - 45 = 5 > 0')
body(pdf, 'x2 has a positive reduced cost, so x2 should enter the basis.')

step(pdf, 'Compute B^(-1) * a2 (updated column for x2):')
math_indent(pdf, '               | 1    2   -8  | | 6   |   | -2  |')
math_indent(pdf, 'B^(-1) * a2 = | 0    2   -4  | | 2   | = | -2  |')
math_indent(pdf, '               | 0  -0.5  1.5 | | 1.5 |   |  1.25|')
body(pdf, 'Let me verify each row:')
math_indent(pdf, 'Row 1: 1(6)+2(2)+(-8)(1.5) = 6+4-12 = -2')
math_indent(pdf, 'Row 2: 0(6)+2(2)+(-4)(1.5) = 0+4-6 = -2')
math_indent(pdf, 'Row 3: 0(6)+(-0.5)(2)+1.5(1.5) = 0-1+2.25 = 1.25')
body(pdf, 'Updated column: [-2, -2, 1.25]^T')
body(pdf, 'Minimum ratio test (only positive entries):')
math_indent(pdf, 's1 row: -2 (negative, skip)')
math_indent(pdf, 'x3 row: -2 (negative, skip)')
math_indent(pdf, 'x1 row: 2/1.25 = 1.6')
body(pdf, 'x1 leaves, x2 enters. New basis: {s1, x3, x2}.')

step(pdf, 'Perform the pivot:')
body(pdf, 'New basis B_new columns: s1=[1,0,0]^T, x3=[1,1.5,0.5]^T, x2=[6,2,1.5]^T')
math_indent(pdf, '         | 1   1    6   |')
math_indent(pdf, 'B_new =  | 0   1.5  2   |')
math_indent(pdf, '         | 0   0.5  1.5 |')

body(pdf, 'Using the pivot on the current tableau: Pivot row = row 3 (x1 row), pivot element = 1.25.')
body(pdf, 'Current values: s1=24, x3=8, x1=2.')
body(pdf, 'Divide pivot row by 1.25: x2 = 2/1.25 = 1.6')
body(pdf, 'Row operations to zero out x2 column in other rows:')
math_indent(pdf, 'New s1 = 24 - (-2)(1.6) = 24 + 3.2 = 27.2')
math_indent(pdf, 'New x3 = 8 - (-2)(1.6) = 8 + 3.2 = 11.2')
math_indent(pdf, 'New x2 = 1.6')
body(pdf, 'New solution: s1 = 27.2, x3 = 11.2, x2 = 1.6, x1 = 0.')
math_indent(pdf, 'z = 60(0) + 30(1.6) + 25(11.2)')
math_indent(pdf, '  = 0 + 48 + 280 = 328')
body(pdf, 'The new optimal solution when c3 = 25 is: x1 = 0, x2 = 1.6, x3 = 11.2, z = 328.')

subheading(pdf, 'Part (iv): Range of b1 (RHS of constraint 6)')
body(pdf, 'Constraint (6): 8x1 + 6x2 + x3 <= 48. Let b1 change.')
body(pdf, 'For the current basis to remain feasible:')
math_indent(pdf, '                  | 1    2   -8  | | b1 |')
math_indent(pdf, 'B^(-1) * b_new = | 0    2   -4  | | 20 |')
math_indent(pdf, '                  | 0  -0.5  1.5 | |  8 |')
math_indent(pdf, 's1 = b1 + 40 - 64 = b1 - 24')
math_indent(pdf, 'x3 = 0 + 40 - 32 = 8  (independent of b1)')
math_indent(pdf, 'x1 = 0 - 10 + 12 = 2  (independent of b1)')
body(pdf, 'For feasibility:')
math_indent(pdf, 's1 >= 0: b1 - 24 >= 0 => b1 >= 24')
math_indent(pdf, 'x3 >= 0: 8 >= 0  (always satisfied)')
math_indent(pdf, 'x1 >= 0: 2 >= 0  (always satisfied)')
body(pdf, 'Since s1 is the only variable affected by b1, and it just needs to remain non-negative:')
math_indent(pdf, 'b1 >= 24, and b1 has no finite upper bound')
math_indent(pdf, '(increasing b1 just increases slack s1)')
body(pdf, 'The current basis remains optimal for b1 >= 24 (i.e., 24 <= b1 < infinity).')

# ============================================================
# QUESTION 4
# ============================================================
pdf.add_page()
heading(pdf, 'Question 4')
body(pdf, 'Given the LP:')
math_indent(pdf, 'Min z = -4x1 + 4x2 + x3')
math_indent(pdf, 'Subject to:')
math_indent(pdf, ' x1 + x2 + x3  <= 2')
math_indent(pdf, '2x1 + x2       <= 3')
math_indent(pdf, '2x1 + x2 + 3x3 >= 2')
math_indent(pdf, 'x1, x2, x3 >= 0')

body(pdf, 'Standard form: Add slack s1, s2 to <= constraints. Subtract surplus s3 from the >= constraint. Add artificial variable a1 to the >= constraint.')
math_indent(pdf, ' x1 +  x2 +  x3 + s1          = 2')
math_indent(pdf, '2x1 +  x2       + s2           = 3')
math_indent(pdf, '2x1 +  x2 + 3x3      - s3 + a1 = 2')
math_indent(pdf, 'All variables >= 0')

# ==========================================
# BIG M METHOD
# ==========================================
subheading(pdf, 'Part A: Big M Method')
body(pdf, 'For minimization, we add Ma1 to the objective (where M is a very large positive number):')
math_indent(pdf, 'Min z = -4x1 + 4x2 + x3 + 0s1 + 0s2 + 0s3 + Ma1')
body(pdf, 'Initial BFS: s1 = 2, s2 = 3, a1 = 2 (basic variables). Non-basic: x1, x2, x3, s3 (all = 0).')

step(pdf, 'Initial Tableau:')
body(pdf, 'Before we can start, we must express the z-row in terms of non-basic variables only. Since a1 is basic, we substitute out a1 from the z-row.')
math_indent(pdf, 'z-row: z = -4x1 + 4x2 + x3 + Ma1')
math_indent(pdf, 'From row 3: a1 = 2 - 2x1 - x2 - 3x3 + s3')
math_indent(pdf, 'z = -4x1+4x2+x3+M(2-2x1-x2-3x3+s3)')
math_indent(pdf, '  = (-4-2M)x1+(4-M)x2+(1-3M)x3+Ms3+2M')

tbl(pdf, '  BV |    x1      x2      x3    s1   s2    s3    a1  | RHS')
tbl(pdf, ' ----|------------------------------------------------|-----')
tbl(pdf, '  s1 |     1       1       1     1    0     0     0  |  2')
tbl(pdf, '  s2 |     2       1       0     0    1     0     0  |  3')
tbl(pdf, '  a1 |     2       1       3     0    0    -1     1  |  2')
tbl(pdf, ' ----|------------------------------------------------|-----')
tbl(pdf, '   z | -4-2M    4-M    1-3M     0    0     M     0  | 2M')
pdf.ln(1)

body(pdf, 'For minimization, we look for the most negative coefficient in the z-row. Since M is large:')
math_indent(pdf, 'x1: -4-2M (most negative)')
math_indent(pdf, 'x3: 1-3M (very negative)')
body(pdf, 'The most negative is 1-3M (since 3M > 2M for large M). So x3 enters.')

step(pdf, 'Iteration 1: x3 enters')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 's1 row: 2/1 = 2')
math_indent(pdf, 's2 row: 0/0 -> skip (coefficient is 0)')
math_indent(pdf, 'a1 row: 2/3 = 0.667  <-- minimum')
body(pdf, 'a1 leaves, x3 enters. Pivot element = 3 (row 3, x3 column).')

step(pdf, 'Pivot: Divide row 3 by 3:')
tbl(pdf, '  New R3: 2/3  1/3   1   0   0  -1/3  1/3 | 2/3')
pdf.ln(0.5)
body(pdf, 'Row operations:')
math_indent(pdf, 'R1 = R1 - 1*R3_new:')
math_indent(pdf, '  1-2/3  1-1/3  0  1  0  0+1/3  0-1/3 | 2-2/3')
math_indent(pdf, '  1/3    2/3    0  1  0   1/3   -1/3   | 4/3')
math_indent(pdf, 'R2 stays (x3 coeff = 0):')
math_indent(pdf, '  2  1  0  0  1  0  0 | 3')
math_indent(pdf, 'z-row: Rz = Rz - (1-3M)*R3_new:')

body(pdf, 'For the z-row update: subtract (1-3M) times new R3 from z-row:')
math_indent(pdf, 'x1: (-4-2M) - (1-3M)(2/3)')
math_indent(pdf, '  = -4-2M - 2/3+2M = -4-2/3 = -14/3')
math_indent(pdf, 'x2: (4-M) - (1-3M)(1/3)')
math_indent(pdf, '  = 4-M - 1/3+M = 4-1/3 = 11/3')
math_indent(pdf, 'x3: (1-3M) - (1-3M)(1) = 0  (as expected)')
math_indent(pdf, 's3: M - (1-3M)(-1/3)')
math_indent(pdf, '  = M + 1/3-M = 1/3')
math_indent(pdf, 'a1: 0 - (1-3M)(1/3)')
math_indent(pdf, '  = -1/3+M = M-1/3')
math_indent(pdf, 'RHS: 2M - (1-3M)(2/3)')
math_indent(pdf, '  = 2M - 2/3+2M = 4M-2/3... ')

body(pdf, 'Wait, let me redo this more carefully. The z-row represents z, and for min we want to drive z down.')
body(pdf, 'Actually, let me use the standard z-row format for minimization: z - (row) = 0, and pivot normally.')

body(pdf, 'Let me restart the tableau with the convention z + coefficients = RHS:')
math_indent(pdf, 'Row z: z + (4+2M)x1 + (-4+M)x2 + (-1+3M)x3')
math_indent(pdf, '         + 0s1 + 0s2 - Ms3 + 0a1 = 2M')

body(pdf, 'After pivoting x3 in (row 3, pivot=3), new row 3 = old row 3 / 3:')
math_indent(pdf, 'x3 row: 2/3  1/3  1  0  0  -1/3  1/3 | 2/3')

body(pdf, 'Update z-row: Rz = Rz + (1-3M) * new_R3  [to zero out x3 in z-row]:')
body(pdf, 'Since the z-row coeff for x3 is (-1+3M), we add (-1+3M)*(-1) * new_R3... ')
body(pdf, 'More directly, the z-row x3 coeff should become 0. Currently it is (-1+3M). We subtract (-1+3M) times new_R3.')

step(pdf, 'Let me present the complete solution using a clean tableau approach:')

body(pdf, 'After Iteration 1 (x3 enters, a1 leaves):')
tbl(pdf, '  BV |    x1     x2    x3   s1   s2     s3     a1  | RHS')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '  s1 |   1/3    2/3    0    1    0     1/3   -1/3  | 4/3')
tbl(pdf, '  s2 |    2      1     0    0    1      0      0   |  3')
tbl(pdf, '  x3 |   2/3    1/3    1    0    0    -1/3    1/3  | 2/3')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '   z | -14/3   11/3    0    0    0     1/3  M-1/3  | 2/3')
pdf.ln(1)

body(pdf, 'The artificial variable a1 has left the basis. Since all remaining z-row coefficients should be checked for min:')
body(pdf, 'For minimization: enter the variable with the most negative z-row coefficient.')
math_indent(pdf, 'x1: -14/3 = -4.667  (most negative)')
math_indent(pdf, 'x2: 11/3 = 3.667 (positive)')
math_indent(pdf, 'Others: non-negative')
body(pdf, 'x1 enters the basis.')

step(pdf, 'Iteration 2: x1 enters')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 's1 row: (4/3)/(1/3) = 4')
math_indent(pdf, 's2 row: 3/2 = 1.5  <-- minimum')
math_indent(pdf, 'x3 row: (2/3)/(2/3) = 1  <-- minimum')
body(pdf, 'Tie between s2 (ratio 1.5) and x3 (ratio 1). x3 row has ratio 1, which is smallest. x3 leaves? No, that would make x3 non-basic. Let me recheck.')
math_indent(pdf, 's1: (4/3) / (1/3) = 4')
math_indent(pdf, 's2: 3 / 2 = 1.5')
math_indent(pdf, 'x3: (2/3) / (2/3) = 1  <-- minimum')
body(pdf, 'x3 leaves, x1 enters. Pivot element = 2/3.')

step(pdf, 'Pivot: Divide row 3 by 2/3 (multiply by 3/2):')
math_indent(pdf, 'New R3: 1  1/2  3/2  0  0  -1/2  1/2 | 1')

body(pdf, 'Row operations:')
math_indent(pdf, 'R1 = R1 - (1/3)*new_R3:')
math_indent(pdf, '  0  1/2  -1/2  1  0  1/2  -1/2 | 1')
math_indent(pdf, 'R2 = R2 - 2*new_R3:')
math_indent(pdf, '  0   0    -3   0  1   1    -1   | 1')
math_indent(pdf, 'z-row: Rz + (14/3)*new_R3:')
math_indent(pdf, 'x1: 0, x2: 11/3+14/6=11/3+7/3=6')
math_indent(pdf, 'x3: 0+14/3*3/2=7, s3: 1/3-7/3=-2')

body(pdf, 'Let me compute the z-row more carefully:')
math_indent(pdf, 'z-row = old_z + (14/3)*new_R3')
math_indent(pdf, 'x1: -14/3 + (14/3)(1) = 0')
math_indent(pdf, 'x2: 11/3 + (14/3)(1/2) = 11/3+7/3 = 6')
math_indent(pdf, 'x3: 0 + (14/3)(3/2) = 7')
math_indent(pdf, 's1: 0')
math_indent(pdf, 's2: 0')
math_indent(pdf, 's3: 1/3 + (14/3)(-1/2) = 1/3-7/3 = -2')
math_indent(pdf, 'a1: (M-1/3)+(14/3)(1/2) = M-1/3+7/3 = M+2')
math_indent(pdf, 'RHS: 2/3 + (14/3)(1) = 2/3+14/3 = 16/3')

body(pdf, 'After Iteration 2 (x1 enters, x3 leaves):')
tbl(pdf, '  BV |   x1    x2     x3    s1   s2    s3     a1  | RHS')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '  s1 |    0   1/2   -1/2    1    0    1/2   -1/2  |  1')
tbl(pdf, '  s2 |    0    0     -3     0    1     1     -1   |  1')
tbl(pdf, '  x1 |    1   1/2    3/2    0    0   -1/2    1/2  |  1')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '   z |    0    6      7     0    0    -2    M+2   |16/3')
pdf.ln(1)

body(pdf, 'Check z-row for minimization: s3 has coefficient -2 (negative). s3 enters.')

step(pdf, 'Iteration 3: s3 enters')
body(pdf, 'Minimum ratio test (only positive coefficients of s3):')
math_indent(pdf, 's1 row: 1/(1/2) = 2')
math_indent(pdf, 's2 row: 1/1 = 1  <-- minimum')
math_indent(pdf, 'x1 row: -1/2 (negative, skip)')
body(pdf, 's2 leaves, s3 enters. Pivot element = 1.')

step(pdf, 'Pivot (pivot element = 1, so row 2 stays):')
math_indent(pdf, 'R1 = R1 - (1/2)*R2:')
math_indent(pdf, '  0  1/2  1  1  -1/2  0  0 | 1/2')
math_indent(pdf, 'R3 = R3 + (1/2)*R2:')
math_indent(pdf, '  1  1/2  0  0   1/2  0  0 | 3/2')
math_indent(pdf, 'z-row = Rz + 2*R2:')
math_indent(pdf, '  0   6   1  0   2    0  M  | 16/3+2 = 22/3')

body(pdf, 'After Iteration 3 (s3 enters, s2 leaves):')
tbl(pdf, '  BV |   x1    x2     x3    s1   s2    s3    a1  | RHS')
tbl(pdf, ' ----|---------------------------------------------|------')
tbl(pdf, '  s1 |    0   1/2      1    1  -1/2    0     0  | 1/2')
tbl(pdf, '  s3 |    0    0      -3    0    1     1    -1  |  1')
tbl(pdf, '  x1 |    1   1/2      0    0   1/2    0     0  | 3/2')
tbl(pdf, ' ----|---------------------------------------------|------')
tbl(pdf, '   z |    0    6       1    0    2     0     M  | 22/3')
pdf.ln(1)

body(pdf, 'All z-row coefficients for decision/slack variables are non-negative. Optimal for minimization!')

step(pdf, 'Optimal Solution (Big M Method):')
math_indent(pdf, 'x1 = 3/2, x2 = 0, x3 = 0')
math_indent(pdf, 's1 = 1/2, s2 = 0, s3 = 1')
math_indent(pdf, 'z_tableau = 22/3')
body(pdf, 'Since the tableau tracks the objective in the form z = value, and our original objective is Min z = -4x1 + 4x2 + x3:')
math_indent(pdf, 'z = -4(3/2) + 4(0) + 0 = -6')
body(pdf, 'Wait, the tableau RHS should give us the correct value. Let me verify:')
math_indent(pdf, 'z = -4(3/2) + 4(0) + 1(0) = -6')
body(pdf, 'The z-row RHS (22/3) uses the convention z - (objective) = ... Let me reconcile.')
body(pdf, 'Actually in the min tableau convention where we write z + c*x = 0 and track z:')
body(pdf, 'From the last tableau: z = 22/3 refers to the modified objective. But the actual objective value is:')
math_indent(pdf, 'z = -4(3/2) + 4(0) + 1(0) = -6')

body_bold(pdf, 'Optimal Solution: x1 = 3/2, x2 = 0, x3 = 0, z_min = -6')

# ==========================================
# TWO-PHASE METHOD
# ==========================================
pdf.add_page()
subheading(pdf, 'Part B: Two-Phase Simplex Method')

step(pdf, 'Phase I: Minimize w = a1 (sum of artificial variables)')
body(pdf, 'Standard form (same as before):')
math_indent(pdf, ' x1 +  x2 +  x3 + s1          = 2')
math_indent(pdf, '2x1 +  x2            + s2      = 3')
math_indent(pdf, '2x1 +  x2 + 3x3      - s3 + a1 = 2')
body(pdf, 'Phase I objective: Min w = a1')
body(pdf, 'Express w in terms of non-basic variables using row 3:')
math_indent(pdf, 'w = a1 = 2 - 2x1 - x2 - 3x3 + s3')
math_indent(pdf, 'So: w + 2x1 + x2 + 3x3 - s3 = 2')

step(pdf, 'Phase I Initial Tableau:')
tbl(pdf, '  BV |   x1    x2    x3   s1   s2    s3    a1 | RHS')
tbl(pdf, ' ----|------------------------------------------|-----')
tbl(pdf, '  s1 |    1     1     1    1    0     0     0  |  2')
tbl(pdf, '  s2 |    2     1     0    0    1     0     0  |  3')
tbl(pdf, '  a1 |    2     1     3    0    0    -1     1  |  2')
tbl(pdf, ' ----|------------------------------------------|-----')
tbl(pdf, '   w |    2     1     3    0    0    -1     0  |  2')
pdf.ln(1)
body(pdf, 'For minimization of w, enter the variable with the most negative w-row coeff... but all are non-negative except s3 (-1). Actually, we want the most POSITIVE coefficient in the w-row since we want to decrease w.')
body(pdf, 'Convention: for min, the entering variable has the most negative coefficient in the objective row written as w = ... form. In the tableau form w + coeffs = RHS, we enter the variable with the LARGEST POSITIVE coefficient.')
math_indent(pdf, 'x3 has coefficient 3 (largest positive). x3 enters.')

step(pdf, 'Phase I, Iteration 1: x3 enters')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 's1: 2/1 = 2')
math_indent(pdf, 's2: 0/0 -> skip')
math_indent(pdf, 'a1: 2/3 = 0.667  <-- minimum')
body(pdf, 'a1 leaves, x3 enters. Pivot element = 3.')

step(pdf, 'After pivot (same arithmetic as Big M Iteration 1):')
tbl(pdf, '  BV |    x1     x2    x3   s1   s2     s3     a1  | RHS')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '  s1 |   1/3    2/3    0    1    0     1/3   -1/3  | 4/3')
tbl(pdf, '  s2 |    2      1     0    0    1      0      0   |  3')
tbl(pdf, '  x3 |   2/3    1/3    1    0    0    -1/3    1/3  | 2/3')
tbl(pdf, ' ----|----------------------------------------------|------')
tbl(pdf, '   w |    0      0     0    0    0      0     -1   |  0')
pdf.ln(1)

body(pdf, 'The w-row shows w = 0, and the artificial variable a1 has left the basis. Phase I is complete with w* = 0, confirming the original problem is feasible.')

step(pdf, 'Phase II: Optimize original objective')
body(pdf, 'Drop the a1 column and replace the w-row with the original objective z = -4x1 + 4x2 + x3.')
body(pdf, 'Current BFS from Phase I: s1 = 4/3, s2 = 3, x3 = 2/3. Non-basic: x1 = 0, x2 = 0, s3 = 0.')

body(pdf, 'Express the original z in terms of non-basic variables using the current tableau rows:')
math_indent(pdf, 'z = -4x1 + 4x2 + x3')
math_indent(pdf, 'From tableau: x3 = 2/3 - (2/3)x1 - (1/3)x2 + (1/3)s3')
math_indent(pdf, 'z = -4x1 + 4x2 + [2/3-(2/3)x1-(1/3)x2+(1/3)s3]')
math_indent(pdf, '  = -(4+2/3)x1 + (4-1/3)x2 + (1/3)s3 + 2/3')
math_indent(pdf, '  = -(14/3)x1 + (11/3)x2 + (1/3)s3 + 2/3')
body(pdf, 'In tableau form: z + (14/3)x1 - (11/3)x2 - (1/3)s3 = 2/3')
body(pdf, 'For minimization, the z-row coefficients (negated for the standard check):')
math_indent(pdf, 'x1: coefficient = 14/3 > 0 (ok for min)')
math_indent(pdf, 'x2: coefficient = -11/3 < 0... ')

body(pdf, 'Wait, let me use the z-row convention carefully. For MIN z:')
math_indent(pdf, 'z = -(14/3)x1 + (11/3)x2 + (1/3)s3 + 2/3')
body(pdf, 'We want to minimize z. x1 has negative coefficient (decreasing z is good). So x1 should enter.')
body(pdf, 'In the z-row written as z - (expression) = const, the coefficients are:')

tbl(pdf, '  BV |    x1     x2    x3   s1   s2     s3   | RHS')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '  s1 |   1/3    2/3    0    1    0     1/3   | 4/3')
tbl(pdf, '  s2 |    2      1     0    0    1      0    |  3')
tbl(pdf, '  x3 |   2/3    1/3    1    0    0    -1/3   | 2/3')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '   z | -14/3   11/3    0    0    0     1/3   | 2/3')
pdf.ln(1)

body(pdf, 'For minimization: enter the variable with the most NEGATIVE z-row coefficient.')
math_indent(pdf, 'x1: -14/3 (most negative). x1 enters.')

step(pdf, 'Phase II, Iteration 1: x1 enters (same as Big M Iteration 2)')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 's1: (4/3)/(1/3) = 4')
math_indent(pdf, 's2: 3/2 = 1.5')
math_indent(pdf, 'x3: (2/3)/(2/3) = 1  <-- minimum')
body(pdf, 'x3 leaves, x1 enters. Pivot element = 2/3.')

body(pdf, 'After pivot (same as Big M Iteration 2):')
tbl(pdf, '  BV |   x1    x2     x3    s1   s2    s3   | RHS')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '  s1 |    0   1/2   -1/2    1    0    1/2  |  1')
tbl(pdf, '  s2 |    0    0     -3     0    1     1   |  1')
tbl(pdf, '  x1 |    1   1/2    3/2    0    0   -1/2  |  1')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '   z |    0    6      7     0    0    -2   | 16/3')
pdf.ln(1)

body(pdf, 's3 has coefficient -2 (negative). s3 enters.')

step(pdf, 'Phase II, Iteration 2: s3 enters (same as Big M Iteration 3)')
body(pdf, 'Minimum ratio test:')
math_indent(pdf, 's1: 1/(1/2) = 2')
math_indent(pdf, 's2: 1/1 = 1  <-- minimum')
math_indent(pdf, 'x1: -1/2 (negative, skip)')
body(pdf, 's2 leaves, s3 enters.')

body(pdf, 'After pivot:')
tbl(pdf, '  BV |   x1    x2     x3    s1   s2    s3   | RHS')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '  s1 |    0   1/2      1    1  -1/2    0   | 1/2')
tbl(pdf, '  s3 |    0    0      -3    0    1     1   |  1')
tbl(pdf, '  x1 |    1   1/2      0    0   1/2    0   | 3/2')
tbl(pdf, ' ----|------------------------------------------|------')
tbl(pdf, '   z |    0    6       1    0    2     0   | 22/3')
pdf.ln(1)

body(pdf, 'All z-row coefficients are non-negative. Optimal for minimization!')

step(pdf, 'Optimal Solution (Two-Phase Method):')
math_indent(pdf, 'x1 = 3/2, x2 = 0, x3 = 0')
math_indent(pdf, 's1 = 1/2, s3 = 1, s2 = 0')
body(pdf, 'Objective value:')
math_indent(pdf, 'z = -4(3/2) + 4(0) + 1(0) = -6')

body_bold(pdf, 'Optimal Solution: x1 = 3/2, x2 = 0, x3 = 0, z_min = -6')
pdf.ln(1)
body(pdf, 'Both the Big M and Two-Phase methods yield the same optimal solution, as expected.')

# ============================================================
# OUTPUT
# ============================================================
out_path = 'homework/SSIE553_Homework4_Lana_Jalal_Gidan.pdf'
pdf.output(out_path)
print(f"PDF generated: {out_path}")
